/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:5b328145-18a1-4318-bff7-750e384862b4",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_RhGpgzed3",
    "aws_user_pools_web_client_id": "42c623v1a6dja3ph2j5guaksvv",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "scraperapi",
            "endpoint": "https://a03c6x8ck5.execute-api.ap-south-1.amazonaws.com/staging",
            "region": "ap-south-1"
        }
    ]
};


export default awsmobile;
